name: Run Tests

on:
  pull_request:
    types: [labeled]

jobs:
  mockoon-test:
    if: ${{ github.event.label.name == 'mock-test' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run test
        run: echo "Hello World from mockoon"

  normal-test:
    if: ${{ github.event.label.name != 'mock-test' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run test
        run: echo "Hello World"
